### ISSUE TITLE
make a first release in opam?

### ISSUE THREAD

**Issue by samoht** [pqwy/lru#1]
You know the rule, if it's not in opam it doesn't exist :-)

and it's just a `topkg tag && topkg bistro` away anyway.

**Comment by pqwy** [comment]
@samoht 
Beh, @dbuenzli was harassing me about the [lack of balancing](https://github.com/pqwy/lru-map/blob/0be337d5f156c7964903fab6234e2248ad3283cc/src/lru_map.mli#L19-L21) in the functional case, so I had to do a completely [different](https://github.com/pqwy/psq) thing. Let me delete most of what is here and rewrap a `psq` as an LRU cache...

**Comment by pqwy** [comment]
@samoht Getting [there](https://github.com/ocaml/opam-repository/pull/7891). Also with per-binding weights that you mentioned.
