### ISSUE TITLE
Peek support

### ISSUE THREAD

**Issue by g2p** [pqwy/lru#4]
I would like to be able to access an element of a mutable LRU without promoting it.
Something like `LRU.M.S.peek key lru`, returning a value option without changing the existing order.

A related need I have is to be notified of dropped values, although I don't know what the best API would be for that.

**Comment by pqwy** [comment]
Something like 4c8bfedb20f85fe0ebab4c38d80c5b65a237f863?

**Comment by g2p** [comment]
Excellent; thank you!

**Comment by pqwy** [comment]
Iz win. Sry for the lag, can't pay close attention to gh these days.
